--CIS_530 - Lab Assignment 2_2
--Name: Aaron Daniels
--ID: 2430989
--Object: Creating a Relational Database using SQL and SQL server/Oracle Database 11g

CREATE DATABASE COMPANY_DANIE; 
GO
USE COMPANY_DANIE; 
CREATE TABLE EMPLOYEE( 
 FNAME VARCHAR(25) NOT NULL, 
 MINIT CHAR, 
 LNAME VARCHAR(25) NOT NULL, 
 SSN CHAR(9) NOT NULL, 
 BDATE DATE, 
 [ADDRESS] VARCHAR(50) NOT NULL, 
 SEX CHAR NOT NULL, 
 SALARY DECIMAL(18,2), 
 SUPERSSN
 DNO
);

CREATE TABLE DEPARTMENT(
 [NAME] VARCHAR(25) NOT NULL, 
 NUMBER TINYINT NOT NULL,
 MGR_SSN
 MGR_START_DATE
);

CREATE TABLE DEPT_LOCATIONS(
  DNUMBER
  DLOCATION
)

CREATE TABLE PROJECT(
  PNAME VARCHAR,
  PNUMBER TINYINT,
  PLOCATION
  DNUM
)

CREATE TABLE WORKS_ON(
  ESSN CHAR(9)
  PNO
  HOURS
)
CREATE TABLE DEPENDANT(
 [NAME] VARCHAR,
 SEX CHAR
 BIRTHDATE DATE,
 RELATIONSHIP VARCHAR,
)